name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build APK
        run: |
          npm install -g @bubblewrap/cli
          # Using 'build' with --skipSigning and answering 'yes' to all system prompts
          yes | bubblewrap build --skipSigning || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Up-Nepa-Osun
          path: ./*.apk
          
